# Nome do ambiente Conda
name: knime_dl_mac

channels:
  - defaults
  - conda-forge

dependencies:
  - _tflow_select=2.3.0
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - appnope=0.1.2
  - arrow-cpp=5.0.0
  - astor=0.8.1
  - attrs=21.4.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - backcall=0.2.0
  - blas=2.11
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.12.12
  - cairo=1.14.12
  - certifi=2021.5.30
  - coverage=5.5
  - cycler=0.11.0
  - cython=0.29.24
  - dataclasses=0.8
  - decorator=5.1.1
  - fontconfig=2.13.1
  - freetype=2.11.0
  - gast=0.5.3
  - gettext=0.21.0
  - gflags=2.2.2
  - glib=2.69.1
  - glog=0.5.0
  - grpc-cpp=1.40.0
  - grpcio=1.36.1
  - h5py=2.8.0
  - hdf5=1.10.2
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - ipython=7.1.1
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jpeg=9d
  - jpype1=0.6.3
  - jsonschema=3.2.0
  - jupyter_core=4.8.1
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - libblas=3.8.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.8.0
  - libcurl=7.80.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libprotobuf=3.18.0
  - libssh2=1.9.0
  - libthrift=0.15.0
  - libtiff=4.0.9
  - libutf8proc=2.6.1
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.0.3
  - nbformat=4.4.0
  - ncurses=6.3
  - nomkl=3.0
  - numpy=1.16.1
  - numpy-base=1.16.1
  - olefile=0.46
  - openssl=1.1.1w
  - orc=1.7.0
  - pandas=0.23.4
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=21.2.2
  - pixman=0.40.0
  - prompt_toolkit=2.0.10
  - protobuf=3.18.0
  - ptyprocess=0.7.0
  - py4j=0.10.9.2
  - pyarrow=5.0.0
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyrsistent=0.17.3
  - python=3.6.13
  - python-dateutil=2.7.5
  - python_abi=3.6
  - pytz=2021.3
  - pyyaml=5.4.1
  - re2=2021.09.01
  - readline=8.1.2
  - scipy=1.1.0
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.37.2
  - tensorboard=1.12.2
  - tensorflow-mkl=1.12.0
  - termcolor=1.1.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=4.3.3
  - typing_extensions=3.10.0.2
  - wcwidth=0.2.5
  - werkzeug=2.0.3
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
